#cloud-config
# Add groups to the system
# Adds the ubuntu group with members 'root' and 'sys'
# and the empty group hashicorp.
groups:
  - ubuntu: [root,sys]
  - hashicorp

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: terraform
    gecos: terraform
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAvf5eZKoLOPFXJRqcf9vyj1c+XS13AAofSdTdqZGIvphW4vqWny/9M2tTTbmXPrYmBDBRZiA/XxnqDNjlRV78+b87L/lIK2kCg0U2tLImskSZN3OYkfL2H+6UF7nsyls0hLV2Blx7Bkz+m82VsSkI1xUobAXxFPN7+yi5OC1BZGyXKD/ZepCQ4m7LZ+fLF70l+kqAqi+jY1W5M8bwhabEjtwNp1mRNMcNgM1RjzNRKdzCxqB4phXSHlYCn4Vb7S88V5BVYwcxr9vZl33qnUx7GwtxKmkcD/IVmCfU6lZHX0BtjCD+FReSAeN6w45DULSI+mWZP/QoCweU4eKasXmQNQ==

# Downloads the golang package
packages:
  - golang-go

# Sets the GOPATH & downloads the demo payload
runcmd:
  - sudo su terraform
  - sudo mkdir /home/terraform/go
  - sudo chown terraform:hashicorp /home/terraform/go
  - export GOPATH=/home/terraform/go
  - go get github.com/hashicorp/learn-go-webapp-demo
